# Generated by Django 3.2.8 on 2021-12-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('he_f_name', models.CharField(max_length=100)),
                ('he_l_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('he_address', models.CharField(max_length=100)),
                ('introduction', models.TextField(blank=True)),
                ('he_introduction', models.TextField(blank=True)),
                ('he_cv', models.CharField(max_length=300)),
                ('en_cv', models.CharField(max_length=300)),
                ('git_hub', models.CharField(max_length=300)),
                ('linked_in', models.CharField(max_length=300)),
                ('facebook', models.CharField(max_length=300)),
                ('instagram', models.CharField(max_length=300)),
                ('twitter', models.CharField(max_length=300)),
                ('short_intro', models.TextField(blank=True)),
                ('he_short_intro', models.TextField(blank=True)),
                ('photo', models.CharField(max_length=300)),
                ('exp_years', models.IntegerField()),
                ('num_projects', models.IntegerField()),
                ('num_works', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(blank=True, max_length=200)),
                ('info', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(blank=True, max_length=200)),
                ('info', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('info', models.TextField(blank=True)),
                ('photo', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_en', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=300)),
                ('info', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100)),
                ('title_he', models.CharField(max_length=100)),
            ],
        ),
    ]
