# Generated by Django 3.2.8 on 2021-12-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bio',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bio',
            name='en_cv',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='bio',
            name='exp_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bio',
            name='facebook',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='bio',
            name='git_hub',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='bio',
            name='he_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bio',
            name='he_cv',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='bio',
            name='he_f_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bio',
            name='he_l_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bio',
            name='instagram',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='bio',
            name='linked_in',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='bio',
            name='num_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bio',
            name='num_works',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bio',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bio',
            name='photo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='bio',
            name='twitter',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='skill',
            name='info',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='skill',
            name='photo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='title',
            name='title_he',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
