# Generated by Django 3.2.8 on 2021-12-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211215_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
