# Generated by Django 3.2.8 on 2021-12-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_bio_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='action',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
