# Generated by Django 3.2.8 on 2021-12-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211216_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='title',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
