# Generated by Django 3.2.8 on 2021-12-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_project_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='fav_icon',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
